on:
  push:
    branches:
      - main
      - master

name: Github Action

jobs:
  npm-build:
    name: npm build check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run build
  docker-build:
    name: Docker build check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - run: docker build . -t nestjs-boilerplate
