on:
  push:
    branches:
      - main

name: Github Action

jobs:
  build-check:
    name: Build Check
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - run: npm ci
      - run: npm run build
